[package]
name = "eviscerator"
version = "0.1.0"
authors = ["Adam Green <adam.green@kcl.ac.uk>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1.3.1"
#heim = "0.0.7"

[build-dependencies]
fs_extra = "1.1.0"