version: 2
jobs:
  build-debug:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: ls eviscerator-release 
      - run: cp -r pddl/ ./eviscertor-release
      - run: cp ./build/release/eviscerator ./eviscerator-release
  build-release:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscertor-release/pddl
      - run: cp ./build/release/eviscerator ./eviscerator-release
  deploy:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscertor-release/pddl
      - run: cp ./build/release/eviscerator ./eviscerator-release
      - run: zip -r eviscerator-release.zip ./eviscerator-release/
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -t ${GITHUB_TOKEN} -n "`cat version.txt`" ./eviscerator-release.zip
  deploy-prerelease:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscertor-release/pddl
      - run: cp ./build/release/eviscerator ./eviscerator-release
      - run: zip -r eviscerator-release.zip ./eviscerator-release/
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -t ${GITHUB_TOKEN} -n "`cat version.txt` Prerelease" -prerelease ./eviscerator-release.zip
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-debug:
          filters:
            branches:
              ignore:
                - master
      - build-release:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
      - deploy-prerelease:
          filters:
            branches:
              only:
                - prerelease