version: 2
jobs:
  build-debug:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build -p eviscerator --bin eviscerator --target-dir ./build
  build-release:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscerator-release
      - run: cp ./build/release/eviscerator ./eviscerator-release
  deploy:
    docker:
    - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscerator-release
      - run: cp ./build/release/eviscerator ./eviscerator-release
      - run: zip -r eviscerator-release.zip ./eviscerator-release/
      - run: github-release upload -o nergmada -r eviscerator -t "`cat version.txt`" -n "`cat version.txt`" -T ${GITHUB_TOKEN} -d eviscerator-release.zip
  deploy-prerelease:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release -p eviscerator --bin eviscerator --target-dir ./build
      - run: mkdir eviscerator-release
      - run: cp -r pddl/ ./eviscerator-release
      - run: cp ./build/release/eviscerator ./eviscerator-release
      - run: zip -r eviscerator-release.zip ./eviscerator-release/
      - run: github-release upload -o nergmada -r eviscerator -t "`cat version.txt`" -n "`cat version.txt` Prerelease" -T ${GITHUB_TOKEN} -d -b "Pre-release" eviscerator-release.zip
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-debug:
          filters:
            branches:
              ignore:
                - master
      - build-release:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
      - deploy-prerelease:
          filters:
            branches:
              only:
                - prerelease