version: 2
jobs:
  build-debug:
    docker:
    - image: adamfgreen/cppbuild:latest
    steps:
      - checkout
      - run: mkdir cmake-build-debug
      - run: cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ..
      - run: cd cmake-build-debug && cmake --build . --target eviscerator -- -j 4
  build-release:
    docker:
    - image: adamfgreen/cppbuild:latest
    steps:
      - checkout
      - run: mkdir cmake-build-release && cd cmake-build-release
      - run: cd cmake-build-release && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
      - run: cd cmake-build-release && cmake --build . --target eviscerator -- -j 4
  deploy:
    docker:
    - image: adamfgreen/cppbuild:latest
    steps:
      - run: ls
      - checkout
      - run: mkdir cmake-build-release && cd cmake-build-release
      - run: cd cmake-build-release && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
      - run: cd cmake-build-release && cmake --build . --target eviscerator -- -j 4
      - run: cd cmake-build-release && mkdir eviscerator-release
      - run: cd cmake-build-release && cp ./eviscerator eviscerator-release
      - run: cd cmake-build-release && cp -r ./pddl ./eviscerator-release/pddl
      - run: cd cmake-build-release && zip -r -9 eviscerator-release.zip ./eviscerator-release/*
      - run: github-release upload --owner nergmada --repo eviscerator --tag ${sh version.sh} --name `sh version.sh` --body "Pre-release" --token ${GITHUB_TOKEN} --prerelease
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-debug:
          filters:
            branches:
              ignore:
                - master
      - build-release:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
              - master
